name: Kubernetes Manifest Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-kubernetes:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Validate Kubernetes YAML
        run: |
          kubectl apply --dry-run=client --validate=true -f kubernetes/