name: Helm Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  helm-lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm Chart
        run: |
          helm lint ./helm/enterprise-cloud-platform